version: '3.3'

services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
    image: analysis/site:latest
    restart: always
    networks:
      - site
      - analysis
    links:
      - postgres
      - rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - "./env_files/django.env"
      - "./env_files/postgres.env"
      - "./env_files/rabbitmq.env"
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

  postgres:
    image: postgres:latest
    restart: always
    networks:
      - site
    env_file:
      - "./env_files/postgres.env"
    expose:
      - "5432"

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    networks:
      - site
    env_file:
      - "./env_files/rabbitmq.env"
    expose:
      - "5672"
      - "15672"

networks:
  site:
  analysis:
    external: true

